
champagne - works
db.challenges.insert({"title" : "Champagne Challenge", "description" : "In the next 24 hours open a bottle of champagne by running the back of a chef's knife up the neck or give $50 to the Special Olympics and challenge four friends to do the same. ", "videoUrl" : "https://www.youtube.com/embed/J24UpdvyAvI", "photo" : "http://i59.tinypic.com/24ymrya.png", "createdBy" : [ { "name" : "Trevor", "userId" : 101010102 } ], "charity" : "Special Olympics", "charityLink": "http://www.sosc.org/donate/information", "responses" : [ ], "goal" : 10000, "minimumDonation" : 50, "totalRaised" : 0 })

drought bucket - works
db.challenges.insert({"title" : "Drought Bucket Challenge", "description" : "In the next 24 hours make a video of yourself dumping a bucket of dirt on your head or give $50 to Friends of the LA River and challenge four friends to do the same.", "videoUrl" : "https://www.youtube.com/embed/TipgAV6hhP8", "photo" : "http://s29.postimg.org/z51qw2j87/Screen_Shot_2015_10_21_at_4_33_04_PM.png", "charityIcon" : "http://www.designeastoflabrea.org/wp-content/uploads/2014/10/FOLAR-lgo-HR_Navy.jpg", "createdBy" : [ { "name" : "Jacque", "userId" : 101010101 } ], "charity" : "Friends of the Los Angeles River", "charityLink": "https://folar.org/donate/", "responses" : [ ], "goal" : 10000, "minimumDonation" : 50, "totalRaised" : 6240 })

pie in the face
db.challenges.insert({"title" : "Pie in the Face Challenge", "description" : "In the next 24 hours take a pie in the face or give $50 to Children’s Hospital Los Angeles and challenge four friends to do the same.", "videoUrl" : "https://www.youtube.com/embed/jU-QXPcq3yQ", "photo" : "http://i62.tinypic.com/2j1n7ya.png", "charityIcon" : "http://www.designeastoflabrea.org/wp-content/uploads/2014/10/FOLAR-lgo-HR_Navy.jpg", "createdBy" : [ { "name" : "Trevor", "userId" : 101010102 } ], "charity" : "Children’s Hospital Los Angeles", "charityLink": "https://secure.chla.org/site/c.ipINKTOAJsG/b.3882839/k.8604/Donate_Today/apps/ka/sd/donorcustom.asp?kntaw30544=F6913AFAA481481E9EA994B9EDAD8875", "responses" : [ ], "goal" : 10000, "minimumDonation" : 50, "totalRaised" : 6240 })

4 liters challenge - works
db.challenges.insert({"title" : "4 LITERS CHALLENGE", "description" : "We challenge you to live one day in water poverty. For 24 hours, use just #4Liters of water for everything you do and change the way you think about water forever more info at 4liters.org. ", "videoUrl" : "https://www.youtube.com/embed/dNs8s2t1yWg", "photo" : "http://s13.postimg.org/60u6qnyuf/Screen_Shot_2015_10_21_at_4_39_23_PM.png", "createdBy" : [ { "name" : "Jason", "userId" : 101010103 } ], "charity" : "DIGDEEP", "charityLink": "https://www.4liters.org/donate", "responses" : [ ], "goal" : 10000, "minimumDonation" : 50, "totalRaised" : 0 })

db.challenges.insert({"title" : "Champagne Challenge", "description" : "In the next 24 hours open a bottle of champagne by running the back of a chef's knife up the neck or give $50 to the Special Olympics and challenge four friends to do the same. ", "videoUrl" : "https://www.youtube.com/embed/J24UpdvyAvI", "photo" : "http://i59.tinypic.com/24ymrya.png", "createdBy" : [ { "name" : "Trevor", "userId" : 101010102 } ], "charity" : "Special Olympics", "charityLink": "http://www.sosc.org/donate/information", "responses" : [ ], "goal" : 10000, "minimumDonation" : 50, "totalRaised" : 0 })
