
//drought bucket Challenge - works
// db.challenges.insert({"title" : "Drought Bucket Challenge", "description" : "In the next 24 hours make a video of yourself dumping a bucket of dirt on your head or give $50 to Friends of the LA River and challenge four friends to do the same.", "videoUrl" : "https://www.youtube.com/embed/TipgAV6hhP8?autoplay=1", "photo" : "http://s29.postimg.org/z51qw2j87/Screen_Shot_2015_10_21_at_4_33_04_PM.png", "charityIcon" : "http://www.designeastoflabrea.org/wp-content/uploads/2014/10/FOLAR-lgo-HR_Navy.jpg", "createdBy" : [ { "name" : "Jacque", "userId" : 101010101 } ], "charity" : "Friends of the Los Angeles River", "responses" : [ ], "goal" : 10000, "minimumDonation" : 50, "totalRaised" : 6240 })

//////pie in th eface challenge, tested works
// db.challenges.insert({"title" : "Pie in the Face Challenge", "description" : "In the next 24 hours take a pie in the face or give $50 to Children’s Hospital Los Angeles and challenge four friends to do the same.", "videoUrl" : "https://www.youtube.com/embed/Aps6g1I5Dm4", "photo" : "http://s7.postimg.org/3wf5jvgq3/Screen_Shot_2015_10_21_at_4_34_29_PM.png", "charityIcon" : "http://www.designeastoflabrea.org/wp-content/uploads/2014/10/FOLAR-lgo-HR_Navy.jpg", "createdBy" : [ { "name" : "Trevor", "userId" : 101010102 } ], "charity" : "Children’s Hospital Los Angeles", "responses" : [ ], "goal" : 10000, "minimumDonation" : 50, "totalRaised" : 6240 })

///////Special Olympics -- works
// db.challenges.insert({"title" : "Champagne Challenge", "description" : "In the next 24 hours open a bottle of champagne by running the back of a chef's knife up the neck or give $50 to the Special Olympics and challenge four friends to do the same. ", "videoUrl" : "https://www.youtube.com/embed/J24UpdvyAvI", "photo" : "http://s23.postimg.org/45ia7xesb/Screen_Shot_2015_10_21_at_4_36_21_PM.png", "createdBy" : [ { "name" : "Trevor", "userId" : 101010102 } ], "charity" : "Special Olympics", "responses" : [ ], "goal" : 10000, "minimumDonation" : 50, "totalRaised" : 0 })

///////4 Liter Challenge - works
// db.challenges.insert({"title" : "Four Liter Challenges", "description" : "We challenge you to live one day in water poverty. For 24 hours, use just #4Liters of water for everything you do and change the way you think about water forever more info at 4liters.org. ", "videoUrl" : "https://www.youtube.com/embed/dNs8s2t1yWg", "photo" : "http://s13.postimg.org/60u6qnyuf/Screen_Shot_2015_10_21_at_4_39_23_PM.png", "createdBy" : [ { "name" : "Jason", "userId" : 101010103 } ], "charity" : "4Liters.org", "responses" : [ ], "goal" : 10000, "minimumDonation" : 50, "totalRaised" : 0 })
